version: "3.9"
services:
    rabbitmq:
        # RabbitMQ 3.8.27
        image: rabbitmq:3.8-management
        container_name: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - ./rabbitmq/etc/:/etc/rabbitmq/
            - ./rabbitmq/data/:/var/lib/rabbitmq/
            - ./rabbitmq/logs/:/var/log/rabbitmq/
